from decimal import Decimal


REFERRAL_REWARD_INVITER = Decimal("25.00")
REFERRAL_REWARD_INVITEE = Decimal("10.00")
REFERRAL_REWARD_TRIGGER = "joined_group"
REFERRAL_REWARD_MINIMUM_JOIN_SUBTOTAL = Decimal("150.00")
