from django.urls import path

from .auth_views import (
    ForgotPasswordConfirmOTPView,
    ForgotPasswordRequestOTPView,
    GoogleAuthView,
    LoginView,
    MobileLoginView,
    MobileLogoutView,
    MobileRefreshSessionView,
    MobileSignupView,
    LogoutView,
    RefreshSessionView,
    SignupAvailabilityView,
    SignupRequestOTPView,
    SignupView,
)
from .views import (
    AcceptGroupInviteView,
    ActivateGroupPurchaseView,
    AddMoneyView,
    CloseGroupView,
    DeactivateGroupInviteLinkView,
    ConfirmGroupAccessView,
    CreateGroupView,
    DashboardView,
    GenerateGroupInviteLinkView,
    GroupChatInboxView,
    GroupChatView,
    GroupInviteInfoView,
    GroupListView,
    GroupReviewView,
    HealthCheckView,
    JoinGroupView,
    LeaveGroupView,
    MarkAllNotificationsReadView,
    MarkNotificationReadView,
    MyGroupDetailView,
    MyGroupsView,
    MyReferralCodeView,
    NotificationView,
    PayoutAccountView,
    ProfileView,
    RazorpayWebhookView,
    RazorpayXPayoutWebhookView,
    ReportGroupAccessIssueView,
    RefundGroupFundsView,
    RequestCredentialRevealView,
    RevealCredentialView,
    SubmitPurchaseProofView,
    SubscriptionListView,
    TransactionHistoryView,
    ValidateReferralCodeView,
    VerifyWalletTopupView,
    WalletPayoutSyncView,
    WithdrawMoneyView,
)

urlpatterns = [
    path('health/', HealthCheckView.as_view()),
    path('signup/check-availability/', SignupAvailabilityView.as_view()),
    path('signup/request-otp/', SignupRequestOTPView.as_view()),
    path('signup/', SignupView.as_view()),
    path('mobile/signup/', MobileSignupView.as_view()),
    path('login/', LoginView.as_view()),
    path('mobile/login/', MobileLoginView.as_view()),
    path('auth/google/', GoogleAuthView.as_view()),
    path('auth/refresh/', RefreshSessionView.as_view()),
    path('mobile/auth/refresh/', MobileRefreshSessionView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('mobile/auth/logout/', MobileLogoutView.as_view()),
    path('forgot-password/request-otp/', ForgotPasswordRequestOTPView.as_view()),
    path('forgot-password/confirm-otp/', ForgotPasswordConfirmOTPView.as_view()),
    path('create-group/', CreateGroupView.as_view()),
    path('join-group/', JoinGroupView.as_view()),
    path('invite/generate/', GenerateGroupInviteLinkView.as_view()),
    path('invite/accept/', AcceptGroupInviteView.as_view()),
    path('invite/info/', GroupInviteInfoView.as_view()),
    path('invite/<int:link_id>/deactivate/', DeactivateGroupInviteLinkView.as_view()),
    path('referral/my-code/', MyReferralCodeView.as_view()),
    path('referral/validate/', ValidateReferralCodeView.as_view()),
    path('leave-group/', LeaveGroupView.as_view()),
    path('credentials/request-reveal/', RequestCredentialRevealView.as_view()),
    path('credentials/reveal/', RevealCredentialView.as_view()),
    path('groups/', GroupListView.as_view()),
    path('group-chats/', GroupChatInboxView.as_view()),
    path('groups/<int:group_id>/chat/', GroupChatView.as_view()),
    path('groups/<int:group_id>/reviews/', GroupReviewView.as_view()),
    path('add-money/', AddMoneyView.as_view()),
    path('payments/razorpay/create-order/', AddMoneyView.as_view()),
    path('payments/razorpay/verify/', VerifyWalletTopupView.as_view()),
    path('payments/razorpay/webhook/', RazorpayWebhookView.as_view()),
    path('payments/razorpayx/webhook/', RazorpayXPayoutWebhookView.as_view()),
    path('wallet/payout-account/', PayoutAccountView.as_view()),
    path('withdraw-money/', WithdrawMoneyView.as_view()),
    path('wallet/payouts/<int:payout_id>/sync/', WalletPayoutSyncView.as_view()),
    path('transactions/', TransactionHistoryView.as_view()),
    path('dashboard/', DashboardView.as_view()),
    path('notifications/', NotificationView.as_view()),
    path('notifications/mark-all-read/', MarkAllNotificationsReadView.as_view()),
    path('notifications/<int:notification_id>/read/', MarkNotificationReadView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('subscriptions/', SubscriptionListView.as_view()),
    path('my-groups/', MyGroupsView.as_view()),
    path('my-groups/<int:group_id>/', MyGroupDetailView.as_view()),
    path('my-groups/<int:group_id>/close/', CloseGroupView.as_view()),
    path('my-groups/<int:group_id>/submit-proof/', SubmitPurchaseProofView.as_view()),
    path('groups/<int:group_id>/confirm-access/', ConfirmGroupAccessView.as_view()),
    path('groups/<int:group_id>/report-access-issue/', ReportGroupAccessIssueView.as_view()),
    path('my-groups/<int:group_id>/activate/', ActivateGroupPurchaseView.as_view()),
    path('my-groups/<int:group_id>/refund/', RefundGroupFundsView.as_view()),
]
