from django.urls import path

from .views import (
    ActivateGroupPurchaseView,
    AddMoneyView,
    CloseGroupView,
    ConfirmGroupAccessView,
    CreateGroupView,
    DashboardView,
    ForgotPasswordConfirmOTPView,
    ForgotPasswordRequestOTPView,
    GroupChatInboxView,
    GroupChatView,
    GroupListView,
    GroupReviewView,
    JoinGroupView,
    LeaveGroupView,
    LoginView,
    MarkAllNotificationsReadView,
    MarkNotificationReadView,
    MyGroupDetailView,
    MyGroupsView,
    NotificationView,
    ProfileView,
    RazorpayWebhookView,
    ReportGroupAccessIssueView,
    RefundGroupFundsView,
    RequestCredentialRevealView,
    RevealCredentialView,
    SignupView,
    SubmitPurchaseProofView,
    SubscriptionListView,
    TransactionHistoryView,
    VerifyWalletTopupView,
    WithdrawMoneyView,
)

urlpatterns = [
    path('signup/', SignupView.as_view()),
    path('login/', LoginView.as_view()),
    path('forgot-password/request-otp/', ForgotPasswordRequestOTPView.as_view()),
    path('forgot-password/confirm-otp/', ForgotPasswordConfirmOTPView.as_view()),
    path('create-group/', CreateGroupView.as_view()),
    path('join-group/', JoinGroupView.as_view()),
    path('leave-group/', LeaveGroupView.as_view()),
    path('credentials/request-reveal/', RequestCredentialRevealView.as_view()),
    path('credentials/reveal/', RevealCredentialView.as_view()),
    path('groups/', GroupListView.as_view()),
    path('group-chats/', GroupChatInboxView.as_view()),
    path('groups/<int:group_id>/chat/', GroupChatView.as_view()),
    path('groups/<int:group_id>/reviews/', GroupReviewView.as_view()),
    path('add-money/', AddMoneyView.as_view()),
    path('payments/razorpay/create-order/', AddMoneyView.as_view()),
    path('payments/razorpay/verify/', VerifyWalletTopupView.as_view()),
    path('payments/razorpay/webhook/', RazorpayWebhookView.as_view()),
    path('withdraw-money/', WithdrawMoneyView.as_view()),
    path('transactions/', TransactionHistoryView.as_view()),
    path('dashboard/', DashboardView.as_view()),
    path('notifications/', NotificationView.as_view()),
    path('notifications/mark-all-read/', MarkAllNotificationsReadView.as_view()),
    path('notifications/<int:notification_id>/read/', MarkNotificationReadView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('subscriptions/', SubscriptionListView.as_view()),
    path('my-groups/', MyGroupsView.as_view()),
    path('my-groups/<int:group_id>/', MyGroupDetailView.as_view()),
    path('my-groups/<int:group_id>/close/', CloseGroupView.as_view()),
    path('my-groups/<int:group_id>/submit-proof/', SubmitPurchaseProofView.as_view()),
    path('groups/<int:group_id>/confirm-access/', ConfirmGroupAccessView.as_view()),
    path('groups/<int:group_id>/report-access-issue/', ReportGroupAccessIssueView.as_view()),
    path('my-groups/<int:group_id>/activate/', ActivateGroupPurchaseView.as_view()),
    path('my-groups/<int:group_id>/refund/', RefundGroupFundsView.as_view()),
]
