import PublicPageShell from "../components/PublicPageShell";
import PublicBusinessIdentity from "../components/PublicBusinessIdentity";

const sections = [
  {
    title: "Information we collect",
    body:
      "ShareVerse collects information you provide directly and information generated by your use of the platform.",
    points: [
      "Account data such as name, username, email address, phone number, profile details, and verification-related information.",
      "Platform activity such as listings, joins, chats, ratings, support requests, proof uploads, dispute reports, and access-confirmation actions.",
      "Wallet and payout data such as ledger entries, payment status, withdrawal requests, and transaction references.",
      "Technical and security data such as device, browser, IP, login, OTP, and abuse-prevention logs.",
    ],
  },
  {
    title: "How we use information",
    body:
      "We use personal information to operate the platform and protect users, payments, and complaint workflows.",
    points: [
      "To create and secure accounts, authenticate users, and recover access when needed.",
      "To run groups, wallet activity, payment verification, support handling, dispute reviews, and buy-together confirmation flows.",
      "To prevent fraud, enforce policy, investigate complaints, and improve platform reliability.",
      "To send transactional notices such as OTPs, purchase-proof requests, access confirmations, payout updates, refund notices, and support replies.",
    ],
  },
  {
    title: "Processors and third-party categories",
    body:
      "ShareVerse uses third-party service providers to run core product functions. These providers may process data only as needed for the relevant service.",
    points: [
      "Payment processing providers for wallet top-ups, payment verification, refunds, and payout-related operations.",
      "Hosting and infrastructure providers for the web app, API, database, file storage, and uptime monitoring.",
      "Email, OTP, and authentication providers for account verification, password resets, and sign-in features such as Google authentication.",
      "Security, logging, and support tooling used to investigate incidents, track platform failures, and respond to disputes or complaints.",
    ],
  },
  {
    title: "Retention windows",
    body:
      "ShareVerse keeps different categories of data for different operational periods. These windows may be extended when a dispute, complaint, fraud review, legal hold, or payment issue is open.",
    points: [
      "Authentication and security logs: normally up to 12 months.",
      "Support tickets, complaint records, and moderation evidence: normally up to 24 months after closure.",
      "Group chats, proof uploads, and listing activity: normally up to 24 months after the related group closes.",
      "Wallet, payout, refund, dispute, and ledger records: normally up to 8 years from the transaction date.",
      "Inactive accounts with no unresolved payment or dispute history: normally reviewed for deletion or anonymization after 24 months of inactivity.",
    ],
  },
  {
    title: "Your rights and requests",
    body:
      "You can request access, correction, deletion review, or other privacy help by contacting ShareVerse through the published support and compliance channels.",
    points: [
      "Requests should include your username, the email or phone tied to the account, and a short description of the request.",
      "ShareVerse normally acknowledges privacy requests within 5 business days and aims to respond within 30 days, subject to identity verification and legal or payment-record retention requirements.",
      "Deletion requests may be denied or delayed for information that must be retained for fraud prevention, dispute handling, chargeback response, tax or accounting needs, or legal compliance.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <PublicPageShell
      eyebrow="Privacy policy"
      title="How ShareVerse collects, uses, and protects member information."
      intro="This page explains how ShareVerse handles account, payment, chat, proof, and support data in day-to-day operations. It is designed to match the live product flows and the support channels published on the site."
    >
      <div className="grid gap-4">
        {sections.map((section) => (
          <article
            key={section.title}
            className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm md:p-6"
          >
            <h2 className="text-xl font-semibold text-slate-950">{section.title}</h2>
            <p className="mt-3 text-sm leading-7 text-slate-600 md:text-base">{section.body}</p>
            <ul className="mt-4 grid gap-2 text-sm leading-7 text-slate-600 md:text-base">
              {section.points.map((point) => (
                <li key={point} className="rounded-[18px] border border-slate-200 bg-slate-50 px-4 py-3">
                  {point}
                </li>
              ))}
            </ul>
          </article>
        ))}
      </div>

      <div className="mt-6 rounded-[24px] border border-emerald-200 bg-emerald-50 p-5 text-sm leading-7 text-emerald-950 md:p-6">
        Privacy and data-rights questions should be sent through the published support or compliance email. Include your username, the email linked to the account, and the specific request so the team can verify identity and respond correctly.
      </div>

      <PublicBusinessIdentity title="Who to contact about privacy questions" />
    </PublicPageShell>
  );
}
