import React from "react";
import { useNavigate } from "react-router-dom";
import PublicPageShell from "../components/PublicPageShell";
import PublicBusinessIdentity from "../components/PublicBusinessIdentity";
import useIsMobile from "../hooks/useIsMobile";

const sections = [
  {
    title: "Information we collect",
    body:
      "ShareVerse collects information you provide directly and information generated by your use of the platform.",
    points: [
      "Account data such as name, username, email address, phone number, profile details, and verification-related information.",
      "Platform activity such as listings, joins, chats, ratings, support requests, proof uploads, dispute reports, and access-confirmation actions.",
      "Wallet and payout data such as ledger entries, payment status, withdrawal requests, and transaction references.",
      "Technical and security data such as device, browser, IP, login, OTP, and abuse-prevention logs.",
    ],
  },
  {
    title: "How we use information",
    body:
      "We use personal information to operate the platform and protect users, payments, and complaint workflows.",
    points: [
      "To create and secure accounts, authenticate users, and recover access when needed.",
      "To run groups, wallet activity, payment verification, support handling, dispute reviews, and buy-together confirmation flows.",
      "To prevent fraud, enforce policy, investigate complaints, and improve platform reliability.",
      "To send transactional notices such as OTPs, purchase-proof requests, access confirmations, payout updates, refund notices, and support replies.",
    ],
  },
  {
    title: "Processors and third-party categories",
    body:
      "ShareVerse uses third-party service providers to run core product functions. These providers may process data only as needed for the relevant service.",
    points: [
      "Payment processing providers for wallet top-ups, payment verification, refunds, and payout-related operations.",
      "Hosting and infrastructure providers for the web app, API, database, file storage, and uptime monitoring.",
      "Email, OTP, and authentication providers for account verification, password resets, and sign-in features such as Google authentication.",
      "Security, logging, and support tooling used to investigate incidents, track platform failures, and respond to disputes or complaints.",
    ],
  },
  {
    title: "Retention windows",
    body:
      "ShareVerse keeps different categories of data for different operational periods. These windows may be extended when a dispute, complaint, fraud review, legal hold, or payment issue is open.",
    points: [
      "Authentication and security logs: normally up to 12 months.",
      "Support tickets, complaint records, and moderation evidence: normally up to 24 months after closure.",
      "Group chats, proof uploads, and listing activity: normally up to 24 months after the related group closes.",
      "Wallet, payout, refund, dispute, and ledger records: normally up to 8 years from the transaction date.",
      "Inactive accounts with no unresolved payment or dispute history: normally reviewed for deletion or anonymization after 24 months of inactivity.",
    ],
  },
  {
    title: "Your rights and requests",
    body:
      "You can request access, correction, deletion review, or other privacy help by contacting ShareVerse through the published support and compliance channels.",
    points: [
      "Requests should include your username, the email or phone tied to the account, and a short description of the request.",
      "Account deletion requests can be started in the mobile app from Profile > Account deletion or from https://shareverse.in/account-deletion.",
      "ShareVerse normally acknowledges privacy requests within 5 business days and aims to respond within 30 days, subject to identity verification and legal or payment-record retention requirements.",
      "Deletion requests may be denied or delayed for information that must be retained for fraud prevention, dispute handling, chargeback response, tax or accounting needs, or legal compliance.",
    ],
  },
];

export default function PrivacyPage() {
  const isMobile = useIsMobile();
  const navigate = useNavigate();

  if (isMobile) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col pb-20 selection:bg-brand/20">
        {/* Sticky Header */}
        <div className="sticky top-0 z-40 bg-slate-50/85 backdrop-blur-xl border-b border-slate-200/60 px-4 py-3 flex items-center shadow-sm">
          <button 
            onClick={() => navigate(-1)}
            className="w-10 h-10 flex items-center justify-center rounded-full bg-white shadow-sm border border-slate-200 text-slate-600 active:bg-slate-50 transition-colors"
            aria-label="Go back"
          >
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <div className="flex-1 flex justify-center pr-10">
            <span className="text-[15px] font-bold text-slate-900 tracking-wide">Legal</span>
          </div>
        </div>

        {/* Hero Section */}
        <div className="px-6 pt-8 pb-6 flex flex-col animate-in slide-in-from-bottom-4 duration-500 fade-in">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-100/60 text-[10px] font-bold uppercase tracking-widest text-emerald-700 mb-4 w-fit border border-emerald-200/50">
            <svg className="w-3.5 h-3.5 opacity-80" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            Privacy Policy
          </div>
          <h1 className="text-[32px] font-extrabold text-slate-900 tracking-tight leading-[1.15]">
            How we protect your data
          </h1>
          <p className="mt-3 text-[15px] text-slate-600 leading-relaxed font-medium">
            Learn how ShareVerse handles your account, payment, and support information safely and securely.
          </p>
        </div>

        {/* Terms Sections */}
        <div className="px-4 flex flex-col gap-5 mt-2">
          {sections.map((section, sIdx) => (
            <article 
              key={section.title} 
              className="bg-white rounded-3xl p-6 shadow-sm border border-slate-200/80 animate-in slide-in-from-bottom-4 duration-500 fade-in fill-mode-both"
              style={{ animationDelay: `${Math.min(sIdx * 100, 800)}ms` }}
            >
              <h2 className="text-[18px] font-bold text-slate-900 tracking-tight leading-snug">
                {section.title}
              </h2>
              <p className="mt-3 text-[14px] text-slate-600 leading-relaxed font-medium">
                {section.body}
              </p>
              
              {section.points && section.points.length > 0 && (
                <div className="mt-4 flex flex-col gap-2.5">
                  {section.points.map((point, pIdx) => (
                    <div key={pIdx} className="flex items-start gap-3 bg-slate-50/80 rounded-2xl p-4 border border-slate-100">
                      <div className="mt-1 w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0 shadow-[0_0_8px_rgba(52,211,153,0.5)]"></div>
                      <p className="text-[13px] text-slate-600 font-medium leading-relaxed">
                        {point}
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </article>
          ))}
        </div>

        {/* Privacy Important Note */}
        <div className="px-4 mt-6 animate-in slide-in-from-bottom-4 duration-500 fade-in fill-mode-both" style={{ animationDelay: "900ms" }}>
          <div className="rounded-3xl border border-emerald-200/60 bg-emerald-50/80 p-5 shadow-sm flex items-start gap-3">
            <svg className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <p className="text-[13px] leading-relaxed text-emerald-900 font-medium">
              Privacy and data-rights questions should be sent through the published support or compliance email. Include your username, the email linked to the account, and the specific request so the team can verify identity.
            </p>
          </div>
        </div>

        {/* Contact/Operator Details */}
        <div className="px-4 mt-8 animate-in slide-in-from-bottom-4 duration-500 fade-in fill-mode-both" style={{ animationDelay: "1000ms" }}>
          <PublicBusinessIdentity 
            title="Who to contact about privacy"
            intro=""
            customContainerClass="bg-slate-900 rounded-[28px] p-6 shadow-xl relative overflow-hidden"
            customTextClass="text-slate-300"
            hideTitle={false}
          />
        </div>

      </div>
    );
  }

  return (
    <PublicPageShell
      eyebrow="Privacy policy"
      title="How ShareVerse collects, uses, and protects member information."
      intro="This page explains how ShareVerse handles account, payment, chat, proof, and support data in day-to-day operations. It is designed to match the live product flows and the support channels published on the site."
    >
      <div className="grid gap-4">
        {sections.map((section) => (
          <article
            key={section.title}
            className="rounded-[var(--sv-radius-card)] border border-slate-200 bg-white p-5 shadow-sm md:p-6"
          >
            <h2 className="text-xl font-semibold text-slate-950">{section.title}</h2>
            <p className="mt-3 text-sm leading-7 text-slate-600 md:text-base">{section.body}</p>
            <ul className="mt-4 grid gap-2 text-sm leading-7 text-slate-600 md:text-base">
              {section.points.map((point) => (
                <li key={point} className="rounded-[18px] border border-slate-200 bg-slate-50 px-4 py-3">
                  {point}
                </li>
              ))}
            </ul>
          </article>
        ))}
      </div>

      <div className="mt-6 rounded-[var(--sv-radius-card)] border border-emerald-200 bg-emerald-50 p-5 text-sm leading-7 text-emerald-950 md:p-6">
        Privacy and data-rights questions should be sent through the published support or compliance email. Include your username, the email linked to the account, and the specific request so the team can verify identity and respond correctly.
      </div>

      <PublicBusinessIdentity title="Who to contact about privacy questions" />
    </PublicPageShell>
  );
}
