# Generated by Django 6.0.4 on 2026-04-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='mode',
            field=models.CharField(choices=[('sharing', 'Sharing'), ('group_buy', 'Group Buy')], default='sharing', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmember',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('collecting', 'Collecting'), ('full', 'Full'), ('purchasing', 'Purchasing'), ('active', 'Active'), ('failed', 'Failed')], default='forming', max_length=20),
        ),
    ]
