# Generated by Django 6.0.4 on 2026-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_is_refunded_group_mode_groupmember_has_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='mode',
            field=models.CharField(choices=[('sharing', 'Sharing'), ('group_buy', 'Group Buy')], default='sharing', max_length=20),
        ),
    ]
