# Generated by Django 6.0.4 on 2026-04-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_subscription_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[
                    ("forming", "Forming"),
                    ("collecting", "Collecting"),
                    ("full", "Full"),
                    ("purchasing", "Purchasing"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("failed", "Failed"),
                ],
                default="forming",
                max_length=20,
            ),
        ),
    ]
