# Generated by Django 6.0.4 on 2026-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_group_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="access_identifier",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="group",
            name="access_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="group",
            name="access_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
