# Generated by Django 6.0.4 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_backfill_buy_together_escrow_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='purchase_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='purchase_proof',
            field=models.FileField(blank=True, null=True, upload_to='purchase-proofs/'),
        ),
        migrations.AddField(
            model_name='group',
            name='purchase_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('collecting', 'Collecting'), ('awaiting_purchase', 'Awaiting Purchase'), ('proof_submitted', 'Proof Submitted'), ('purchasing', 'Purchasing'), ('active', 'Active'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('closed', 'Closed'), ('failed', 'Failed')], default='forming', max_length=20),
        ),
    ]
