# Generated by Django 6.0.4 on 2026-04-10 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_purchase_proof_review_state(apps, schema_editor):
    Group = apps.get_model("core", "Group")
    Group.objects.filter(status="proof_submitted").update(proof_review_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_group_proof_submitted_at_group_purchase_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='proof_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='proof_review_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='proof_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='proof_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_purchase_proof_review_state, migrations.RunPython.noop),
    ]
