# Generated by Django 6.0.4 on 2026-04-11 06:16

from django.db import migrations, models


def backfill_group_buy_access_confirmation(apps, schema_editor):
    GroupMember = apps.get_model("core", "GroupMember")
    GroupMember.objects.filter(
        group__mode="group_buy",
        escrow_status="released",
    ).update(access_confirmed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_group_proof_review_notes_group_proof_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='access_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='access_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_group_buy_access_confirmation, migrations.RunPython.noop),
    ]
