# Generated by Django 6.0.4 on 2026-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_groupmember_access_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='access_issue_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='access_issue_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='access_issue_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('collecting', 'Collecting'), ('awaiting_purchase', 'Awaiting Purchase'), ('proof_submitted', 'Proof Submitted'), ('disputed', 'Disputed'), ('purchasing', 'Purchasing'), ('active', 'Active'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('closed', 'Closed'), ('failed', 'Failed')], default='forming', max_length=20),
        ),
    ]
