# Generated by Django 6.0.4 on 2026-04-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_razorpaywebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayXPayoutWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('payout_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('vpa', 'UPI VPA')], default='bank_account', max_length=20)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_type', models.CharField(default='customer', max_length=20)),
                ('provider_contact_id', models.CharField(blank=True, default='', max_length=100)),
                ('provider_fund_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_holder_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_last4', models.CharField(blank=True, default='', max_length=4)),
                ('vpa_address', models.CharField(blank=True, default='', max_length=255)),
                ('vpa_handle', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WalletPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_subunits', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider', models.CharField(default='razorpayx', max_length=30)),
                ('provider_payout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_contact_id', models.CharField(blank=True, default='', max_length=100)),
                ('provider_fund_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('provider_reference_id', models.CharField(max_length=40, unique=True)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('source_account_number', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], max_length=10)),
                ('purpose', models.CharField(default='payout', max_length=30)),
                ('narration', models.CharField(blank=True, default='', max_length=30)),
                ('destination_label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='created', max_length=20)),
                ('status_details', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('provider_status_source', models.CharField(blank=True, default='', max_length=80)),
                ('utr', models.CharField(blank=True, default='', max_length=120)),
                ('fees', models.PositiveIntegerField(default=0)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet_restored_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='core.payoutaccount')),
                ('refund_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_payout_refund', to='core.transaction')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_payout', to='core.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
