# Generated by Django 6.0.4 on 2026-04-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_groupchatpresence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupchatpresence',
            new_name='core_groupc_group_i_301410_idx',
            old_name='core_groupc_group_i_f7fb62_idx',
        ),
        migrations.RenameIndex(
            model_name='groupchatpresence',
            new_name='core_groupc_group_i_ecef6f_idx',
            old_name='core_groupc_group_i_4f80d6_idx',
        ),
    ]
