# Generated by Django 6.0.4 on 2026-04-24 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps, schema_editor):
    user_model = apps.get_model("core", "User")
    referral_code_model = apps.get_model("core", "ReferralCode")

    for user in user_model.objects.all().iterator():
        if referral_code_model.objects.filter(user=user).exists():
            continue

        while True:
            candidate = f"SV-{uuid.uuid4().hex[:8].upper()}"
            if referral_code_model.objects.filter(code=candidate).exists():
                continue
            referral_code_model.objects.create(user=user, code=candidate)
            break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_core_groupc_group_i_f7fb62_idx_core_groupc_group_i_301410_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='core.group')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('successful_referrals', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('signed_up', 'Signed Up'), ('joined_group', 'Joined Group'), ('rewarded', 'Rewarded')], default='signed_up', max_length=20)),
                ('reward_given', models.BooleanField(default=False)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_entry', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.referralcode')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
    ]
