# Generated by Django 6.0.4 on 2026-05-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_accountdeletionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('chat_message', 'Chat Message')], max_length=20)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment or bullying'), ('hate', 'Hate or abuse'), ('sexual_content', 'Sexual content'), ('violence', 'Violence or threats'), ('spam', 'Spam'), ('scam', 'Scam or fraud'), ('privacy', 'Privacy issue'), ('other', 'Other')], default='other', max_length=40)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_group_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='hidden_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], db_index=True, default='visible', max_length=20),
        ),
        migrations.AddIndex(
            model_name='groupchatmessage',
            index=models.Index(fields=['group', 'moderation_status', 'created_at'], name='core_groupc_group_i_5e883d_idx'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to='core.groupchatmessage'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to='core.group'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_about_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['status', 'created_at'], name='core_conten_status_7f2a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['target_type', 'created_at'], name='core_conten_target__e7f75b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['reporter', 'created_at'], name='core_conten_reporte_2bdf93_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker', 'blocked'], name='core_userbl_blocker_0aa98c_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked', 'created_at'], name='core_userbl_blocked_815bd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked')},
        ),
    ]
