# Generated by Django 6.0.4 on 2026-07-12 07:18

from django.db import migrations, models


def backfill_google_sub(apps, schema_editor):
    User = apps.get_model("core", "User")
    from django.contrib.auth.hashers import is_password_usable
    legacy_google_users = []
    for user in User.objects.all():
        if not is_password_usable(user.password):
            user.google_sub = f"legacy_google_{user.id}"
            legacy_google_users.append(user)
    
    if legacy_google_users:
        User.objects.bulk_update(legacy_google_users, ["google_sub"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill_google_sub, reverse_code=migrations.RunPython.noop),
    ]
