# Generated by Django 6.0.4 on 2026-07-18 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_user_email_unique_ci_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.group'),
        ),
        migrations.AlterField(
            model_name='walletpayout',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp at which approved_by signed off on this payout.', null=True),
        ),
        migrations.AlterField(
            model_name='walletpayout',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who approved this payout before processing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
